### ISSUE TITLE
System.InvalidOperationException: Process has exited, so the requested information is not available.

### ISSUE THREAD

**Issue by gileli121** [BiGilSoft/WindowTop#166]
```
Version: v5.6.8
System.InvalidOperationException: Process has exited, so the requested information is not available.
at System.Diagnostics.Process.EnsureState(State state)
at System.Diagnostics.Process.get_ProcessName()
at WindowTop.Managers.WindowItem.LoadFixedWindowProperties()
at WindowTop.Managers.WindowItem..ctor(IntPtr hwnd, WindowItem shrinkParentWindow, Int32 windowOpacity, Boolean lostWindow)
at WindowTop.Managers.WindowManager.GetNewWindowsAndRefreshZOrders(List`1& windows, Boolean filterIgnoredWindows, Boolean skipInVisibleWindows, Boolean processWindowAdded)
at WindowTop.Managers.WindowManager.Init()
at WindowTop.App.d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by gileli121** [comment]
Fixed
