### ISSUE TITLE
NullReferenceException from WindowTop.UI.Features.Anchor.AnchorItem.AnchorItem_OnLocationChanged

### ISSUE THREAD

**Issue by gileli121** [BiGilSoft/WindowTop#188]
Users reported about this error:

```
Comment: Version: v5.7.8
System.NullReferenceException: Object reference not set to an instance of an object.
at WindowTop.UI.Features.Anchor.AnchorItem.AnchorItem_OnLocationChanged(Object sender, EventArgs e)
at System.Windows.Window.OnLocationChanged(EventArgs e)
at System.Windows.Window.WmMoveChangedHelper()
at System.Windows.Window.WmMoveChanged()
at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Steps to reproduce**
1. Disable the option "Stay away from text or image"
2. Restart the program
3. Enable Anchors
4. Try to move some anchor

**Comment by gileli121** [comment]
Fixed

**Comment by gileli121** [comment]
Fix released in https://github.com/BiGilSoft/WindowTop/releases/tag/v5.7.9
