### ISSUE TITLE
v5.19.2 progress (beta versions)

### ISSUE THREAD

**Issue by gileli121** [BiGilSoft/WindowTop#282]

**Comment by gileli121** [comment]
[WindowTop 5.19.2-beta1 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/10418515/WindowTop.5.19.2-beta1.-.setup.exe.zip)

* A new fix to https://github.com/BiGilSoft/WindowTop/issues/113 
* Improve the grammar of the English texts

**Comment by gileli121** [comment]
[WindowTop 5.19.2-beta2 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/10418579/WindowTop.5.19.2-beta2.-.setup.exe.zip)

* Fixed https://github.com/BiGilSoft/WindowTop/issues/268

**Comment by gileli121** [comment]
[WindowTop 5.19.2-beta3 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/10421125/WindowTop.5.19.2-beta3.-.setup.exe.zip)

* Fixed regression from the last fix for #235, that the app may crash silently
* Improve stability - reduce the probability of getting the error window from #151

**Comment by gileli121** [comment]
[WindowTop 5.19.2-beta4 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/10472126/WindowTop.5.19.2-beta4.-.setup.exe.zip)
* Implemented https://github.com/BiGilSoft/WindowTop/issues/269

**Comment by gileli121** [comment]
[WindowTop 5.19.2-beta6 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/10472188/WindowTop.5.19.2-beta6.-.setup.exe.zip)

* Fixed issue that the toolbar does not show when the "Whitelist the specified programs" is selected and no programs are added to the list (#275)

![image](https://user-images.githubusercontent.com/17680514/213867370-dee028d6-0f0f-4620-8243-f02197b84ee6.png)

This time it will not allow you to use this option if the list is empty.
![image](https://user-images.githubusercontent.com/17680514/213867356-d56df21d-eeab-4ee3-89a8-02b131562d7e.png)

**Comment by gileli121** [comment]
[WindowTop 5.19.2-beta6 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/10528125/WindowTop.5.19.2-beta6.-.setup.exe.zip)

### In this release, the focus was on fixing errors that were reported using the [fatal exception error window](https://github.com/BiGilSoft/WindowTop/issues/151)

* Fixed the fatal exception error:
```
unknown
System.ComponentModel.Win32Exception (0x80004005): El sistema no puede encontrar el archivo especificado
at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
at CQc.rQI.d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at s4.cq.d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at s4.cq.d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

* Potential fix for the fatal exception error:
```
5.19.1
System.NullReferenceException: Object reference not set to an instance of an object.
at JdY.fuz.d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at x6.z1.d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at x6.z1.d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by gileli121** [comment]
[WindowTop 5.19.2-beta7 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/10559665/WindowTop.5.19.2-beta7.-.setup.exe.zip)

Potential fix for:

```
System.NullReferenceException: Object reference not set to an instance of an object.
at System.Windows.Threading.PriorityQueue`1.Dequeue()
at System.Windows.Threading.Dispatcher.ProcessQueue()
at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by gileli121** [comment]
[WindowTop 5.19.2-beta8 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/10561955/WindowTop.5.19.2-beta8.-.setup.exe.zip)

* Fix for possible `InvalidOperationException` exception in RendererManager when killing a renderer process

```
System.InvalidOperationException: No process is associated with this object.
at System.Diagnostics.Process.EnsureState(State state)
at System.Diagnostics.Process.EnsureState(State state)
at System.Diagnostics.Process.get_Id()
at IyC.Mys.fyL()
at IyC.Mys.Iyu()
at QgH.QgV.c__DisplayClass295_0.duO()
at sp6.bpa.fpr(Action , Boolean )
```

* Fixed exception in `HoverPreviewItem` when it sets invalid `Width` value for the hover preview in some cases

```
v5.18.0
System.ArgumentException: '-21' não é um valor válido para a propriedade 'Width'.
em System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
em System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
em MCL.DCj.JCz()
em O2I.j2l.l2W(Action , Boolean )
```

* Fixed exception when removing hotkey via the getting started window via the backspace button

```
v5.19.1
System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.
in iyY.Pyt.ByH(EyM , HotKey )
in w9F.D9n.HotKeyOpacityEditControl_OnHotKeyChanged(Object sender, EventArgs e)
in System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
in System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
in System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
in System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
in System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
in System.Windows.Input.InputManager.ProcessStagingArea()
in System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
in System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
in System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
in System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
in System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
in System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
in System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by gileli121** [comment]
[WindowTop 5.19.2-beta9 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/10582049/WindowTop.5.19.2-beta9.-.setup.exe.zip)

* Fixed regression from beta-3 about the fix for the freeze issue, that the app may silently crash and exist more often
* Improved the recovery logic that was used to avoid the case that the app UI thread froze. The old logic avoided it by allowing the app to crash silently and exit. Now the logic will interrupt the UI thread so the app UI can show the actual fatal error while allowing the user to continue running the app or exit the app and report the error.
* Removed unneeded logs and improved a few logs

**Comment by gileli121** [comment]
[WindowTop 5.19.2-beta10 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/10679289/WindowTop.5.19.2-beta10.-.setup.exe.zip)

* Implemented "Restart program" button in the global error handler:
![image](https://user-images.githubusercontent.com/17680514/217360703-c2aa4f6f-882f-4b75-a338-07141b0ab262.png)
Now you can easily restart the app instead of relaunching the app (useful when the error does not go away until restart)
* Fixed bug in the Microsoft Store version that when enabling a feature like always on top for an elevated window and confirming the admin permission request, the app froze for a few seconds and failed to enable the feature.

**Comment by gileli121** [comment]
[WindowTop 5.19.2-beta11 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/10682408/WindowTop.5.19.2-beta11.-.setup.exe.zip)

* Fixed fatal error in WTToolBarArrow that reported in the Microsoft store version by three users
```
5.19.1
System.NullReferenceException: 未将对象引用设置到对象的实例。
在 UTr.yT7.PT4()
在 UTr.yT7.mTX(IntPtr , Int32 , IntPtr , IntPtr , Boolean& )
在 System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

* Fixed fatal error reported by five users via the Microsoft store version
```
5.19.1
System.NullReferenceException: Object reference not set to an instance of an object.
at JdY.fuz.d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at x6.z1.d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at x6.z1.d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by gileli121** [comment]
Released
